### ISSUE TITLE
Can't run, sadly...

### ISSUE THREAD

**Issue by vallieres** [CinKon/generator-uikit-webapp#1]
Hello,

I installed  your generator and after linking it ran it with yo. I'm getting this error:

    /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9048
                    throw e;
                          ^
    TypeError: Object #<Object> has no method 'on'
        at run (/Users/vallieres/Development/github/generator-uikit-webapp/node_modules/yeoman-generator/lib/base.js:445:21)
        at composeWith (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/base.js:568:15)
        at yoyo._initGenerator (/usr/local/lib/node_modules/yo/yoyo.js:100:8)
        at null.<anonymous> (/usr/local/lib/node_modules/yo/yoyo.js:407:35)
        at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:69:10)
        at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1775:12)
        at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1712:14)

Any idea what is wrong? I'm up to date on everything.

Yeoman 1.3.3
NPM 2.3.0

Thanks

**Comment by vallieres** [comment]
Nevermind, my npm install was totally broken :facepalm:
